// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtbzstbfxbcdlbkvxwvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0YnpzdGJmeGJjZGxia3Z4d3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NjY1NjEsImV4cCI6MjA1NzQ0MjU2MX0.iAG29sLHEnxV-PnWlnzbPZRTRPCYkSFRK78prf7xp8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);